#!/usr/bin/env bash
nvars=($(cat input.nml | sed 's/!.*//g' | sed 's/&.*//g' | sed 's/=.*//g' \
  | tr -d '/,' | xargs))
fvars=($(cat global_variables.f90 | grep -A8 '^\s*namelist' | sed 's/.*\///g' \
  | tr -d ',&' | xargs))
for nvar in ${nvars[@]}; do
  if [[ ! " ${fvars[@]} " =~ " $nvar " ]]; then
    echo "Namelist file parameter \"$nvar\" not in namelist call"
    exit 1
  fi
done
for fvar in ${fvars[@]}; do
  if [[ ! " ${nvars[@]} " =~ " $fvar " ]]; then
    echo "Parameter from namelist call \"$fvar\" not in namelist file."
    exit 1
  fi
done
echo "Namelist file and namelist call have identical variables."

