#!/bin/sh
rm *.o
rm *.mod
rm *.df
ifort -c global_variables.f90
ifort -c forward.f90
ifort -c -mkl ftm.f90
ifort -c -mkl invert.f90
ifort -c -mkl initial.f90
ifort -c -mkl exec.f90
ifort -c -I/opt/hdf4/intel/include -L/opt/hdf4/intel/lib -lmfhdf -ldf -ljpeg -lz  io.f90
ifort -c -mkl main.f90
ifort -O3 "./io.o" "exec.o" "./invert.o" "./ftm.o" "./forward.o" "./global_variables.o" "./main.o" "./initial.o"  -mkl -I/opt/hdf4/intel/include -L/opt/hdf4/intel/lib -lmfhdf -ldf -ljpeg -lz -o "./d.out"


